[versions]
junit-jupiter = "5.9.0"

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.0.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "com.github.sgtsilvio.gradle.metadata", version = "0.3.0" }
