[versions]
junit-jupiter = "5.12.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version = "1.3.1" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
